import { state } from '../../state.js';
import { CREATION_SYSTEMS } from '../../configs/creation-data.js';
import { REWARD_QUALITY_COLORS } from '../../systems/CheatSystem.js';
import { audioManager } from '../../utils/audio-manager.js';

export class CheatSystemScreen {
    constructor() {
        this.overlay = null;
        this.content = null;
        this.closeBtn = null;
        this.isOpeningChest = false;
        this.selectedChooseIndex = null;
        this.ui = state.ui;
    }

    initElements() {
        this.overlay = document.getElementById('cheat-system-overlay');
        this.content = document.getElementById('cheat-system-content');
        this.closeBtn = document.getElementById('close-cheat-system-btn');

        if (this.closeBtn) {
            this.closeBtn.onclick = () => this.close();
        }
    }

    open() {
        if (!this.overlay) this.initElements();
        if (!this.overlay) return;

        this.overlay.classList.remove('hidden');
        audioManager.playSfx('ui_click');
        this.render();
    }

    close() {
        if (!this.overlay) return;
        this.overlay.classList.add('hidden');
        audioManager.playSfx('ui_click');
        
        // Save state immediately upon closing modal
        if (window.game && typeof window.game.saveGame === 'function') {
            window.game.saveGame();
        }
    }

    render() {
        if (!this.content) return;

        const cheatSys = state.systems.cheat;
        if (!cheatSys || !cheatSys.systemId) {
            this.content.innerHTML = `
                <div class="text-center py-10 space-y-4">
                    <i class="ph ph-shield-warning text-4xl text-gray-500"></i>
                    <p class="text-xs text-gray-400 font-ancient">Vô Pháp Cảm Ứng Bàn Tay Vàng</p>
                    <p class="text-[10px] text-gray-600">Đạo hữu chưa chọn Hệ thống hỗ trợ lúc tạo nhân vật.</p>
                </div>
            `;
            return;
        }

        const sysConfig = (CREATION_SYSTEMS || []).find(s => s.id === cheatSys.systemId);
        const sysName = sysConfig ? sysConfig.name : 'Hệ Thống Cheat';
        const sysDesc = sysConfig ? sysConfig.desc : '';

        // Update modal title
        const titleEl = document.getElementById('cheat-system-title');
        if (titleEl) titleEl.textContent = sysName;

        // Render main active system UI or chest/choose sub-minigames if active
        if (cheatSys.pendingRewards) {
            if (cheatSys.claimStyle === 'chest') {
                this.renderChestOpening();
                return;
            } else if (cheatSys.claimStyle === 'choose') {
                this.renderChooseOneOfThree();
                return;
            }
        }

        // Render standard interface
        let subContent = '';
        if (cheatSys.systemId === 'sign_in') {
            subContent = this.getSignInUI(cheatSys);
        } else if (cheatSys.systemId === 'mission') {
            subContent = this.getMissionUI(cheatSys);
        } else if (cheatSys.systemId === 'check_in_loc') {
            subContent = this.getLocationUI(cheatSys);
        }

        this.content.innerHTML = `
            <!-- System Introduction Card -->
            <div class="p-4 rounded-2xl bg-gradient-to-br from-amber-500/10 to-yellow-500/5 border border-amber-500/20 text-center space-y-2">
                <div class="text-[10px] font-ancient text-cultivation-gold uppercase tracking-[0.1em] font-black">${sysName}</div>
                <div class="text-[9px] text-gray-400 italic leading-relaxed">"${sysDesc}"</div>
            </div>

            <!-- Custom System Interaction Area -->
            <div class="space-y-4">
                ${subContent}
            </div>
        `;

        // Bind inner actions
        this.bindActions();
    }

    /**
     * Bind dynamic buttons generated by templates
     */
    bindActions() {
        const cheatSys = state.systems.cheat;
        if (!cheatSys) return;

        const btnSign = document.getElementById('cheat-action-signin');
        if (btnSign) {
            btnSign.onclick = () => {
                if (cheatSys.player.inventory.isFull) {
                    state.ui.toast("Hành trang đã đầy! Vui lòng dọn dẹp rương đồ trước khi ký đảo.", "warning");
                    return;
                }
                audioManager.playSfx('breakthrough');
                const success = cheatSys.actionSignIn();
                if (success) {
                    if (cheatSys.claimStyle === 'direct') {
                        this.showRewardsAlert(cheatSys.signInState.totalDays === 1 ? 'Đăng Nhập Đầu' : 'Điểm Danh Ngày Mới', cheatSys.lastClaimedRewards);
                    }
                    this.render();
                }
            };
        }

        const btnClaimMission = document.getElementById('cheat-action-mission');
        if (btnClaimMission) {
            btnClaimMission.onclick = () => {
                if (cheatSys.player.inventory.isFull) {
                    state.ui.toast("Hành trang đã đầy! Vui lòng dọn dẹp rương đồ trước khi nhận Chí Cao phần thưởng.", "warning");
                    return;
                }
                audioManager.playSfx('level_up');
                const success = cheatSys.actionClaimMission();
                if (success) {
                    if (cheatSys.claimStyle === 'direct') {
                        this.showRewardsAlert('Hoàn Thành Chí Cao Nhiệm Vụ', cheatSys.lastClaimedRewards);
                    }
                    this.render();
                }
            };
        }

        const btnCheckIn = document.getElementById('cheat-action-checkin');
        if (btnCheckIn) {
            btnCheckIn.onclick = () => {
                if (cheatSys.player.inventory.isFull) {
                    state.ui.toast("Hành trang đã đầy! Vui lòng dọn dẹp rương đồ trước khi đánh dấu.", "warning");
                    return;
                }
                audioManager.playSfx('success');
                const success = cheatSys.actionCheckIn();
                if (success) {
                    if (cheatSys.claimStyle === 'direct') {
                        this.showRewardsAlert('Đánh Dấu Thiên Cơ Thành Công', cheatSys.lastClaimedRewards);
                    }
                    this.render();
                }
            };
        }
    }

    /**
     * UI Template for Daily Sign-In System
     */
    getSignInUI(cheatSys) {
        const state = cheatSys.signInState;
        const active = state.available;

        return `
            <div class="p-6 rounded-[2rem] bg-black/40 border border-white/5 text-center space-y-6">
                <div class="space-y-1">
                    <div class="text-[9px] uppercase tracking-wider text-gray-500">Đại Lộ Điểm Danh</div>
                    <div class="text-xl font-bold font-mono text-cultivation-gold">${state.totalDays} ngày</div>
                    <div class="text-[8px] text-gray-600">Mỗi ngày trôi qua đăng nhập sẽ mở ra đại khí vận.</div>
                </div>

                <div class="flex justify-center py-2">
                    <div class="relative flex items-center justify-center w-20 h-20 rounded-full border border-amber-500/20 bg-amber-500/5 animate-pulse">
                        <i class="ph ph-calendar-check text-3xl text-amber-400"></i>
                    </div>
                </div>

                <button id="cheat-action-signin" 
                    ${!active ? 'disabled' : ''}
                    class="w-full py-3.5 ${active ? 'btn-gold animate-pulse text-black font-black' : 'bg-white/5 border border-white/5 text-gray-500 cursor-not-allowed'} font-ancient rounded-2xl uppercase tracking-[0.2em] text-[10px] transition-all duration-300">
                    ${active ? 'KÝ ĐÁO ĐIỂM DANH' : 'ĐÃ KÝ ĐÁO HÔM NAY'}
                </button>
                
                ${!active ? `<p class="text-[8px] text-gray-600 italic">"Hẹn gặp lại đạo hữu vào ngày game tiếp theo!"</p>` : ''}
            </div>
        `;
    }

    /**
     * UI Template for Daily Cheat Mission System
     */
    getMissionUI(cheatSys) {
        const mission = cheatSys.missionState.currentMission;
        if (!mission) {
            return `
                <div class="p-6 rounded-[2rem] bg-black/40 border border-white/5 text-center">
                    <p class="text-[10px] text-gray-500 italic">Đang cảm ứng Thiên Cơ nhiệm vụ...</p>
                </div>
            `;
        }

        const pct = Math.min(100, Math.round((mission.current / mission.target) * 100));
        const active = mission.completed && !mission.claimed;

        return `
            <div class="p-5 rounded-[2rem] bg-black/40 border border-white/5 space-y-5">
                <div class="flex justify-between items-start border-b border-white/5 pb-3">
                    <div class="space-y-1">
                        <span class="text-[8px] uppercase font-bold text-amber-500 tracking-wider">Nhiệm Vụ Chí Cao</span>
                        <h4 class="text-xs font-ancient font-bold text-white tracking-wide">${mission.name}</h4>
                    </div>
                    <span class="text-[8px] font-mono px-2 py-0.5 rounded bg-white/5 border border-white/10 ${mission.completed ? 'text-green-400' : 'text-qi-blue'}">
                        ${mission.completed ? 'ĐÃ XONG' : 'ĐANG LÀM'}
                    </span>
                </div>

                <p class="text-[10px] text-gray-400 leading-relaxed">${mission.desc}</p>

                <!-- Custom Progress Bar -->
                <div class="space-y-1.5">
                    <div class="flex justify-between items-center text-[9px] font-mono text-gray-500">
                        <span>Tiến Độ</span>
                        <span class="font-bold text-white">${mission.current} / ${mission.target} (${pct}%)</span>
                    </div>
                    <div class="h-2 w-full bg-white/5 rounded-full overflow-hidden border border-white/10">
                        <div class="h-full bg-gradient-to-r from-amber-500 to-yellow-400 shadow-[0_0_10px_rgba(245,158,11,0.4)] transition-all duration-500" style="width: ${pct}%"></div>
                    </div>
                </div>

                <div class="pt-2">
                    ${mission.claimed ? `
                        <div class="w-full py-3.5 bg-white/5 border border-white/5 text-gray-500 font-ancient rounded-2xl uppercase tracking-[0.2em] text-[10px] text-center cursor-not-allowed">
                            ĐÃ NHẬN THƯỞNG HÔM NAY
                        </div>
                    ` : `
                        <button id="cheat-action-mission" 
                            ${!active ? 'disabled' : ''}
                            class="w-full py-3.5 ${active ? 'btn-gold animate-bounce text-black font-black' : 'bg-white/5 border border-white/5 text-gray-500 cursor-not-allowed'} font-ancient rounded-2xl uppercase tracking-[0.2em] text-[10px] transition-all duration-300">
                            ${mission.completed ? 'NHẬN CHÍ CAO PHẦN THƯỞNG' : 'CHƯA HOÀN THÀNH'}
                        </button>
                    `}
                </div>
            </div>
        `;
    }

    /**
     * UI Template for Check-In Location System
     */
    getLocationUI(cheatSys) {
        const state = cheatSys.locationState;
        const currentlyHere = cheatSys.canCheckIn();
        const active = currentlyHere && !state.claimed;

        return `
            <div class="p-6 rounded-[2rem] bg-black/40 border border-white/5 text-center space-y-6">
                <div class="space-y-1">
                    <div class="text-[8px] uppercase tracking-wider text-gray-500">Tọa Độ Đánh Dấu Thiên Địa</div>
                    <div class="text-xs font-ancient font-black text-amber-400 uppercase tracking-widest">${state.targetLocName || 'Đang Cảm Ứng'}</div>
                    <div class="text-[8px] text-gray-600">Đến đúng địa điểm thiên địa hội tụ để đánh dấu khí vận.</div>
                </div>

                <!-- Custom Map Compass Indicator -->
                <div class="flex justify-center">
                    <div class="relative flex items-center justify-center w-20 h-20 rounded-full border ${active ? 'border-amber-500 bg-amber-500/10 shadow-[0_0_20px_rgba(245,158,11,0.2)] animate-pulse' : 'border-white/10 bg-white/5'}">
                        <i class="ph ph-compass text-3xl ${active ? 'text-amber-400 animate-spin' : 'text-gray-600'}"></i>
                    </div>
                </div>

                ${state.claimed ? `
                    <div class="w-full py-3.5 bg-white/5 border border-white/5 text-gray-500 font-ancient rounded-2xl uppercase tracking-[0.2em] text-[10px] cursor-not-allowed">
                        ĐÃ ĐÁNH DẤU HÔM NAY
                    </div>
                ` : `
                    <button id="cheat-action-checkin" 
                        ${!active ? 'disabled' : ''}
                        class="w-full py-3.5 ${active ? 'btn-gold animate-pulse text-black font-black' : 'bg-white/5 border border-white/5 text-gray-500 cursor-not-allowed'} font-ancient rounded-2xl uppercase tracking-[0.2em] text-[10px] transition-all duration-300">
                        ĐÁNH DẤU ĐỊA ĐIỂM
                    </button>
                    
                    ${!currentlyHere ? `
                        <div class="text-[8px] text-red-400 font-ancient flex items-center justify-center space-x-1">
                            <i class="ph ph-warning-circle"></i>
                            <span>Tọa độ không khớp. Vui lòng di chuyển đến [${state.targetLocName}]!</span>
                        </div>
                    ` : ''}
                `}
            </div>
        `;
    }

    /**
     * Render the visual Chest Opening minigame
     */
    renderChestOpening() {
        const cheatSys = state.systems.cheat;
        const rewards = cheatSys.pendingRewards;
        if (!rewards) return;

        if (this.isOpeningChest) {
            // Render chest open and showing items
            this.content.innerHTML = `
                <div class="text-center py-6 space-y-6 animate-fade-in">
                    <div class="text-[10px] font-ancient text-cultivation-gold uppercase tracking-[0.1em] font-black">Rương Thiên Cơ Đã Mở!</div>
                    
                    <!-- Pulsing Light Beam & Exploded Chest -->
                    <div class="flex justify-center py-2">
                        <div class="relative w-28 h-28 flex items-center justify-center rounded-full bg-amber-500/10 border border-amber-500/40 shadow-[0_0_40px_rgba(245,158,11,0.3)] animate-ping"></div>
                        <i class="ph ph-package-open text-6xl text-amber-300 absolute mt-4"></i>
                    </div>

                    <!-- Glowing Items list -->
                    <div class="space-y-2.5 max-w-xs mx-auto">
                        ${rewards.map((reward, i) => {
                            const col = REWARD_QUALITY_COLORS[reward.quality] || 'text-gray-400';
                            return `
                                <div class="flex items-center justify-between p-3 rounded-xl bg-white/5 border border-white/10 hover:border-amber-500/25 transition-all duration-300 animate-slide-up" style="animation-delay: ${i * 150}ms">
                                    <div class="flex items-center space-x-3">
                                        <span class="text-lg">${reward.icon}</span>
                                        <div class="text-left">
                                            <div class="text-[10px] font-ancient font-bold text-white tracking-wide">${reward.name}</div>
                                            <div class="text-[8px] ${col} font-bold">${reward.quality}</div>
                                        </div>
                                    </div>
                                    <span class="text-[10px] font-mono text-amber-400 font-bold">x${reward.qty}</span>
                                </div>
                            `;
                        }).join('')}
                    </div>

                    <button id="cheat-claim-chest-btn" 
                        class="w-full py-3.5 btn-gold font-ancient font-black rounded-2xl uppercase tracking-[0.2em] text-[10px] transition-all">
                        THU HỒI VÀO TÚI TRỮ VẬT
                    </button>
                </div>
            `;

            // Claim rewards button
            const btnClaim = document.getElementById('cheat-claim-chest-btn');
            if (btnClaim) {
                btnClaim.onclick = () => {
                    if (cheatSys.player.inventory.isFull) {
                        state.ui.toast("Hành trang đã đầy! Vui lòng dọn dẹp rương đồ trước khi thu hồi.", "warning");
                        return;
                    }
                    this.isOpeningChest = false;
                    cheatSys.applyRewardsDirectly();
                    audioManager.playSfx('ui_click');
                    this.render();
                };
            }
        } else {
            // Initial locked chest screen
            this.content.innerHTML = `
                <div class="text-center py-8 space-y-6">
                    <div class="space-y-1">
                        <div class="text-[8px] font-ancient text-gray-500 uppercase tracking-widest">Khí Vận Điềm Lành Quy Tụ</div>
                        <div class="text-xs font-ancient font-black text-cultivation-gold uppercase tracking-[0.1em]">RƯƠNG THIÊN CƠ BẢO HỘP</div>
                    </div>

                    <!-- Pulsing Chest -->
                    <div class="flex justify-center py-2 cursor-pointer group" id="cheat-chest-container">
                        <div class="relative w-24 h-24 flex items-center justify-center rounded-full bg-amber-500/5 border border-amber-500/20 group-hover:scale-105 transition-all duration-300">
                            <div class="absolute inset-0 rounded-full bg-amber-500/10 animate-ping"></div>
                            <i class="ph ph-package text-5xl text-amber-500 group-hover:text-amber-400 animate-bounce"></i>
                        </div>
                    </div>

                    <p class="text-[9px] text-gray-400 leading-relaxed italic px-4">
                        "Cơ duyên nghịch thiên đang phong ấn bên trong rương bảo hộp. Hãy tập trung tinh thần để mở khóa phá giải phong ấn!"
                    </p>

                    <button id="cheat-open-chest-btn" 
                        class="w-full py-3.5 btn-gold font-ancient font-black rounded-2xl uppercase tracking-[0.2em] text-[10px] animate-pulse">
                        MỞ PHONG ẤN RƯƠNG
                    </button>
                </div>
            `;

            // Open action
            const handleOpen = () => {
                this.isOpeningChest = true;
                audioManager.playSfx('breakthrough');
                this.render();
            };

            const btnOpen = document.getElementById('cheat-open-chest-btn');
            if (btnOpen) btnOpen.onclick = handleOpen;
            const container = document.getElementById('cheat-chest-container');
            if (container) container.onclick = handleOpen;
        }
    }

    /**
     * Render the interactive Tarot Card Flip 3-Choose-1 minigame
     */
    renderChooseOneOfThree() {
        const cheatSys = state.systems.cheat;
        const rewards = cheatSys.pendingRewards;
        if (!rewards) return;

        if (this.selectedChooseIndex !== null) {
            // Visual feedback screen showing the selected card revealed and others shown as faded out
            this.content.innerHTML = `
                <div class="text-center py-6 space-y-6 animate-fade-in">
                    <div class="text-[10px] font-ancient text-cultivation-gold uppercase tracking-[0.1em] font-black font-bold">Lựa Chọn Khí Vận Thành Công!</div>
                    
                    <div class="grid grid-cols-3 gap-3 py-2">
                        ${rewards.map((reward, i) => {
                            const isSelected = i === this.selectedChooseIndex;
                            const col = REWARD_QUALITY_COLORS[reward.quality] || 'text-gray-400';
                            return `
                                <div class="relative p-2.5 rounded-2xl border transition-all duration-500 flex flex-col items-center justify-center space-y-2 h-32
                                    ${isSelected ? 'bg-amber-500/10 border-amber-500 shadow-[0_0_20px_rgba(245,158,11,0.2)] scale-105 z-10' : 'bg-black/80 border-white/5 opacity-30'}">
                                    <span class="text-2xl">${reward.icon}</span>
                                    <div class="text-center space-y-0.5">
                                        <div class="text-[8px] font-ancient font-bold text-white line-clamp-2 leading-tight">${reward.name}</div>
                                        <div class="text-[7px] ${col} font-black">${reward.quality}</div>
                                    </div>
                                    <div class="text-[8px] font-mono text-amber-400 font-bold">x${reward.qty}</div>
                                    ${isSelected ? `
                                        <span class="absolute -top-1.5 -right-1 px-1 py-0.5 rounded bg-amber-500 text-black font-black text-[6px] uppercase tracking-wider font-ancient">Đã Chọn</span>
                                    ` : ''}
                                </div>
                            `;
                        }).join('')}
                    </div>

                    <p class="text-[8px] text-gray-500 leading-relaxed italic px-4">
                        "Khí vận duyên linh đã hòa quyện vào linh căn đạo hữu. Hai bảo vật còn lại đã trôi dạt vào dòng thời không."
                    </p>

                    <button id="cheat-claim-choose-btn" 
                        class="w-full py-3.5 btn-gold font-ancient font-black rounded-2xl uppercase tracking-[0.2em] text-[10px]">
                        XÁC NHẬN VÀ TIẾP TỤC
                    </button>
                </div>
            `;

            // Bind claim confirmation
            const btnClaim = document.getElementById('cheat-claim-choose-btn');
            if (btnClaim) {
                btnClaim.onclick = () => {
                    if (cheatSys.player.inventory.isFull) {
                        state.ui.toast("Hành trang đã đầy! Vui lòng dọn dẹp rương đồ trước khi nhận thưởng.", "warning");
                        return;
                    }
                    const result = cheatSys.chooseReward(this.selectedChooseIndex);
                    this.selectedChooseIndex = null;
                    if (result) {
                        state.ui.toast(`Lựa chọn thành công: Nhận [${result.chosen.name}]!`, 'success');
                    }
                    audioManager.playSfx('ui_click');
                    this.render();
                };
            }
        } else {
            // Interactive 3 face-down cards
            this.content.innerHTML = `
                <div class="text-center py-6 space-y-6">
                    <div class="space-y-1">
                        <div class="text-[8px] font-ancient text-gray-500 uppercase tracking-widest">Nghịch Thiên Cải Mệnh</div>
                        <div class="text-xs font-ancient font-black text-cultivation-gold uppercase tracking-[0.1em]">LỰA CHỌN THIÊN CƠ KHÍ VẬN</div>
                    </div>

                    <div class="grid grid-cols-3 gap-3 py-2">
                        ${[0, 1, 2].map(i => {
                            const labels = ['Bảo Vật', 'Đan Dược', 'Linh Cơ'];
                            return `
                                <div onclick="window.game.screens.cheat.onCardSelected(${i})"
                                    class="relative p-2.5 rounded-2xl border border-amber-500/20 bg-gradient-to-b from-[#111] to-[#050505] hover:border-amber-500/60 hover:scale-105 active:scale-95 transition-all duration-300 flex flex-col items-center justify-center space-y-3 h-32 cursor-pointer shadow-[0_0_15px_rgba(212,175,55,0.05)] group">
                                    <div class="absolute inset-0 bg-gradient-to-r from-transparent via-amber-500/5 to-transparent -translate-x-full group-hover:animate-shine rounded-2xl"></div>
                                    
                                    <!-- Decorative Runes -->
                                    <div class="relative w-8 h-8 flex items-center justify-center rounded-full border border-amber-500/30 bg-amber-500/5">
                                        <span class="text-[10px] font-ancient text-amber-500 font-black animate-pulse">☯</span>
                                    </div>
                                    
                                    <div class="text-center space-y-1 z-10">
                                        <div class="text-[8px] font-ancient font-black text-cultivation-gold tracking-widest">${labels[i]}</div>
                                        <div class="text-[6px] text-gray-500 uppercase">Khí Vận ${i + 1}</div>
                                    </div>
                                </div>
                            `;
                        }).join('')}
                    </div>

                    <p class="text-[8px] text-gray-400 leading-relaxed italic px-4">
                        "Tam đài pháp trận đang trôi nổi trong không hư. Hãy bấm chọn lấy một đạo khí vận tương thích với đạo hạnh của bản thân!"
                    </p>
                </div>
            `;
        }
    }

    /**
     * Card flip click handler (Bound to window global context)
     */
    onCardSelected(index) {
        this.selectedChooseIndex = index;
        audioManager.playSfx('level_up');
        this.render();
    }

    /**
     * Display a beautiful visual popup notification of directly claimed rewards
     */
    showRewardsAlert(title, items) {
        if (!items || items.length === 0) return;
        let content = `<div class="space-y-2 mt-2">`;
        items.slice(0, 3).forEach(item => {
            const col = REWARD_QUALITY_COLORS[item.quality] || 'text-gray-400';
            content += `
                <div class="flex items-center justify-between p-2.5 rounded-xl bg-white/5 border border-white/10">
                    <span class="text-[10px] text-white/80 font-bold">${item.icon} ${item.name} (x${item.qty})</span>
                    <span class="text-[9px] ${col} font-black uppercase font-mono">${item.quality}</span>
                </div>
            `;
        });
        content += `</div>`;

        state.ui.alert(content, title || 'Thiên Cơ Ban Thưởng');
    }
}
